### ISSUE TITLE
Repeating numbers

### ISSUE THREAD

**Issue by glingy** [ronshapiro/minesweeper#1]
When I use a board larger than 10x10, the 0-9 just repeats so I can't tell if it is 9, 19, 29, 39, or 49 in 50x50.

![screen shot 2017-10-29 at 8 28 06 am](https://user-images.githubusercontent.com/17791817/32145297-290ed0ec-bc83-11e7-8bd5-6c12e92a7999.png)

**Comment by ronshapiro** [comment]
This would probably work fine on the left/right since we can just append, but it's probably not great on the top/bottom.

One option is to make the `0`'s a different color, so it's easier to distinguish wow many you're in. Or maybe below every `0` (and above on the top line) we could include '(N0)' to help out. 

I've honestly not used this in a few years, but I'm happy to help figure this out. What would you like most?

**Comment by glingy** [comment]
I don't really know and probably won't use it that much anyway, but the (N0) idea seems best. I had just been searching for a terminal minesweeper for a few minutes and found this. Thanks for the help though.

**Comment by ronshapiro** [comment]
Do you mind checking out the `cursor` branch and see if you like that version more? I think I should be able to make it work for both but just in case

**Comment by ronshapiro** [comment]
Should be fixed in the latest commit. Here's a screenshot with a board of 111x111 (chopped off due to window size):

![board](https://i.imgur.com/yZh5SEs.png)
